### ISSUE TITLE
Fix access-token

### ISSUE THREAD

**Issue by agbeltran** [icatproject/icatproject.github.io#38]
the GA is failing for PRs (see https://github.com/icatproject/icatproject.github.io/pull/37 and https://github.com/icatproject/icatproject.github.io/pull/28) and we need to investigate and provide an access-token

**Comment by louise-davies** [comment]
I think this is due to those PRs coming in from forks, which means they don't have access to the encrypted secret (see https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow). However, we only need the access token for publishing, which only happens once merged (and thus will definitely have the access token) so there should be a way to fix this issue for builds only

**Comment by louise-davies** [comment]
See https://github.com/enriikke/gatsby-gh-pages-action/issues/27
aka we should either use the solution in that thread or switch to the main github pages action

**Comment by agbeltran** [comment]
thanks @louise-davies - this is now fixed 182232e230309febceab714b496a9d13f1a26cf3
